# Site settings
title: Personal Website
description: 
baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://dyang5.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: dyang5
user_description: I’m a graduating senior from The College Preparatory School in Oakland, CA. In the fall, I will be attending Swarthmore College (hopefully in person)! As of now, I am planning to pursue Math and Computer Science, and am also interested in Economics as well. This website was made for personal experimentation purposes, please contact me if you have any questions at all.

user_title: Student at Swarthmore College
email: not.dyang@gmail.com
twitter_username: 
github_username:  dyang5
gplus_username: 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
